-- 1. Последовательность для ID задач
CREATE SEQUENCE IF NOT EXISTS tasks_seq START WITH 1 INCREMENT BY 50;

-- 2. Таблица пользователей
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    original_avatar_file_name VARCHAR(512),
    avatar_s3_key VARCHAR(255) UNIQUE,
    deleted BOOLEAN NOT NULL DEFAULT false
    version BIGINT NOT NULL DEFAULT 0
);

-- 3. Таблица ролей
CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

-- 4. Таблица задач
CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    priority VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL CHECK (status IN ('NEW','IN_PROGRESS','TESTING','REVIEW','COMPLETED')),
    artist_id BIGINT,
    owner_id BIGINT NOT NULL REFERENCES users(id),
    deadline TIMESTAMP(6) NOT NULL,
    comment VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT false
    version BIGINT NOT NULL DEFAULT 0
);

-- 5. Таблица вложений
CREATE TABLE IF NOT EXISTS task_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    s3_key VARCHAR(512) NOT NULL UNIQUE,
    content_type VARCHAR(255),
    file_size BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    task_id BIGINT,
    CONSTRAINT fk_task_attachments_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE
);

-- 6. Таблица уведомлений
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message VARCHAR(255),
    is_read BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT REFERENCES users(id),
    task_id BIGINT REFERENCES tasks(id)
);

-- 7. Таблица связи пользователей и ролей
CREATE TABLE IF NOT EXISTS user_roles (
    role_id BIGINT NOT NULL REFERENCES roles(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    PRIMARY KEY (role_id, user_id)
);

-- 8. Таблица избранных задач пользователей
CREATE TABLE IF NOT EXISTS user_favourite_tasks (
    task_id BIGINT NOT NULL REFERENCES tasks(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    PRIMARY KEY (task_id, user_id)
);